
= Image API

== Description
====
Image API allows upload of product images to be stored and used within iZettle applications.
The API returns an `imageUrl` that can be added to a desired product using the Product Library API.
Images can be uploaded using a byte array or a static URL, the image will be eventually available for look up from
within iZettle apps or via `imageUrls` returned by the API.

NOTE: JPG does not exist as `imageFormat`, you must use "JPEG" for .jpg images.

====

=== URL
https://image.izettle.com

=== OAuth scopes
- `WRITE:PRODUCT`

*Parameters:*

[grid="none", frame="none", cols="20%,10%,10%,10%,50%"]
|===
|Name|Type|In|Required/Optional|Description

|`imageFormat`|_string_|_body_|*_required_*|Image format of the picture [BMP,GIF,JPEG,PNG,TIFF]`.
|`imageData`|_string_|_body_|_optional_|The image as a byte array.
|`imageUrl|_string_|_body_|_optional_|URL to an existing image.
|`imageLookupKey`|_string_|_body_|_optional_|Image lookup key.
|===

NOTE: Either `imageData` or `imageUrl` must be present, but not both.

=== Examples:

*Request:*

`POST /v2/images/organizations/{organizationUuid}/products`
[source, json]
----
{
  "imageFormat": "JPEG",
  "imageUrl": "https://example.com/image.jpg"
}
----

*Response:*

[source, json]
----
{
  "imageLookupKey": "0SFqIEwSEeWQb_kt6ixqNQ-10TukFTMEaekExOP02bdsw.jpeg",
  "imageUrls": [
    "https://image.izettle.com/productimage/o/0SFqIEwSEeWQb_kt6ixqNQ-10TukFTMEaekExOP02bdsw.jpeg",
    "https://image.izettle.com/productimage/L/0SFqIEwSEeWQb_kt6ixqNQ-10TukFTMEaekExOP02bdsw.jpeg"
  ]
}
----
Where `o` is a `2000*2000px` and `L` is a `560*560px` image.

To apply this uploaded image on a product, use the first URL provided in the `imageUrls` array.
