= Purchase API

== Description

====
Provides information about purchases made through iZettle.
====

=== Base URL

https://purchase.izettle.com

=== OAuth scopes

- `READ:PURCHASE`

'''

==== Fetch purchase history

Returns a list of purchases for organization.
Purchases up to three years old are available to fetch.

`GET /purchases/v2`

[%collapsible]
====
*Parameters*

[cols="15%,10%,10%,10%,55%"]
|===
|Name|Type|In|Required/Optional|Description

|lastPurchaseHash|string|query|optional|A value from "lastPurchaseHash" from the result of a previous history query, to continue listing purchases from the next record after the previous query.
|startDate|string|query|optional|The start date (inclusive) for purchases to be retrieved from until today or endDate if provided. By default `startDate` is resolved to three years back.
|endDate|string|query|optional|The last date (exclusive) for purchases to be retrieved until.
|limit|string|query|optional|The maximum number of records to return. Max value of limit is 1000.
|descending|string|query|optional|When true, returns purchases with the highest timestamp first.  When false, returns purchases with the lowest timestamp first. Defaults to false if not specified.
|===


*Responses*

`Status: 200 OK` - Successful, response json is returned. +
`Status: 401 Unauthorized` - You were not authorized to execute this operation. +
`Status: 429 Too Many Requests` - You hit the rate limit. Retry request later.

*Examples*

* Fetching limited number of purchases in descending order(most recent first).
+
--
_Request:_

`GET /purchases/v2?limit=2&descending=true`

_Response:_

`Status: 200 OK`

[source,json]
----
{
  "purchases": [
    {
      "source": "POS",
      "purchaseUUID": "Odi3BjWLEeuollr2KMFqhA",
      "amount": 5000,
      "vatAmount": 535,
      "taxAmount": 535,
      "country": "SE",
      "currency": "SEK",
      "timestamp": "2020-12-02T17:16:20.028+0000",
      "gpsCoordinates": {
        "longitude": 18.03388854523291,
        "latitude": 59.3160400390625,
        "accuracyMeters": 65
      },
      "purchaseNumber": 120092,
      "globalPurchaseNumber": 391839,
      "userDisplayName": "Sven Andersson",
      "userId": 11111,
      "organizationId": 11111,
      "products": [
        {
          "quantity": "1",
          "productUuid": "2d6315d0-9c60-1111-bc3f-04cc0b41ebd4",
          "variantUuid": "a5169ee0-ba72-1111-ba39-41e31bf3e57b",
          "vatPercentage": 12,
          "unitPrice": 2000,
          "rowTaxableAmount": 1786,
          "name": "Coffee",
          "variantName": "",
          "fromLocationUuid": "97faeaa0-18f4-1111-adfd-a56a099d6f5a",
          "toLocationUuid": "97faeaa0-18f4-1111-9f18-d0f3b2151876",
          "id": "0",
          "type": "PRODUCT",
          "libraryProduct": true
        },
        {
          "quantity": "1",
          "productUuid": "2d62c7b0-9c60-11e5-acbe-d387d7298c3c",
          "variantUuid": "a5169ee0-ba72-11e6-9aa8-19b96b962055",
          "vatPercentage": 12,
          "unitPrice": 3000,
          "rowTaxableAmount": 2679,
          "name": "Chocolate chip cookie",
          "variantName": "",
          "fromLocationUuid": "97faeaa0-18f4-11e7-adfd-a56a099d6f5a",
          "toLocationUuid": "97faeaa0-18f4-11e7-9f18-d0f3b2151876",
          "autoGenerated": false,
          "id": "1",
          "type": "PRODUCT",
          "details": {},
          "libraryProduct": true
        }
      ],
      "discounts": [],
      "payments": [
        {
          "uuid": "41fad608-358b-11eb-a9cf-adce2fdbc505",
          "amount": 5000,
          "type": "IZETTLE_CARD",
          "createdAt": "2020-12-02T17:16:05.000+0000",
          "attributes": {
            "transactionStatusInformation": "E800",
            "cardHolderVerificationMethod": "PIN",
            "maskedPan": "11111*******1111",
            "cardPaymentEntryMode": "EMV",
            "referenceNumber": "LQTTTTT",
            "authorizationCode": "111111",
            "cardType": "MASTERCARD",
            "terminalVerificationResults": "0000008000",
            "applicationIdentifier": "A0000000041010",
            "applicationName": "MASTERCARD"
          }
        }
      ],
      "cashRegister": {
        "displayName": "Kassa 2",
        "uuid": "YdVwSn4i111DZepjFuVBw"
      },
      "receiptCopyAllowed": true,
      "references": {
        "checkoutUUID": "39d8b706-358b-11eb-a997-5bf729c06b85"
      },
      "created": "2020-12-03T17:16:20.028+0000",
      "refunded": false,
      "purchaseUUID1": "39d8b706-358b-11eb-a896-5af628c16a84",
      "groupedVatAmounts": {
        "12.0": 5000
      },
      "refund": false
    },
    {
      "source": "POS",
      "purchaseUUID": "Bm5SpjWJEeuollr2KMFqhA",
      "amount": 3500,
      "vatAmount": 375,
      "taxAmount": 375,
      "country": "SE",
      "currency": "SEK",
      "timestamp": "2020-12-03T17:00:24.879+0000",
      "gpsCoordinates": {
        "longitude": 18.033884556629268,
        "latitude": 59.316070556640625,
        "accuracyMeters": 65
      },
      "purchaseNumber": 120091,
      "globalPurchaseNumber": 391838,
      "userDisplayName": "Sven Andersson",
      "userId": 1713921,
      "organizationId": 14184411,
      "products": [
        {
          "quantity": "1",
          "productUuid": "b108fd90-9c3e-11e5-9cf5-b7187b674ae8",
          "variantUuid": "a5169ee0-ba72-11e6-bd41-a12a8359ddc6",
          "vatPercentage": 12,
          "unitPrice": 3500,
          "rowTaxableAmount": 3125,
          "name": "Coffee with milk",
          "variantName": "",
          "fromLocationUuid": "97faeaa0-18f4-11e7-adfd-a56a099d6f5a",
          "toLocationUuid": "97faeaa0-18f4-11e7-9f18-d0f3b2151876",
          "autoGenerated": false,
          "id": "0",
          "type": "PRODUCT",
          "details": {},
          "libraryProduct": true
        }
      ],
      "discounts": [],
      "payments": [
        ...
        }
      ],
      "cashRegister": {
        "displayName": "Kassa 2",
        "uuid": "YdVwSn4iEemdDZepjFuVBw"
      },
      "receiptCopyAllowed": true,
      "references": {
        "checkoutUUID": "066e52a6-3589-11eb-a997-5bf729c06b85"
      },
      "taxationMode": "INCLUSIVE",
      "taxationType": "VAT",
      "created": "2020-12-03T17:00:24.879+0000",
      "refunded": false,
      "purchaseUUID1": "066e52a6-3589-11eb-a896-5af628c16a84",
       ...
      "groupedVatAmounts": {
        "12.0": 3500
      },
      "refund": false
    }
  ],
  "firstPurchaseHash": "1607015780028Odi3BjWLEeuollr2KMFqhA",
  "lastPurchaseHash": "1607014824879Bm5SpjWJEeuollr2KMFqhA",
  "linkUrls": [
    "<https://purchase.izettle.com/purchases/v2/?limit=2&descending=true&lastPurchaseHash=1607014824879Bm5SpjWJEeuollr2KMFqhA>; rel=\"next\""
  ]
}
----
--

* Fetching all purchases for a merchant.
+
--
*Note:* API consumer should never retrieve all the purchases in one request, since it potentially can put too much load on the server causing request timeout.

Instead, it should request paginated result, using the `limit` and `lastPurchaseHash` parameters.

The `limit` parameter will set the page size, and the `lastPurchaseHash` parameter sets the starting point from where to retrieve purchases.
Every response will contain a `lastPurchaseHash` attribute, which should added to request for the next page.
A prepared URL is also provided in attribute `linkUrls`, if more purchases are to be fetched.

In order to load all purchases, begin with an initial request without the `lastPurchaseHash` parameter, this will retrieve the first _n_ purchases , `limit` parameter should be used to define page size.


`GET /purchases/v2?limit=50&descending=true`

_Response:_

`Status: 200 OK`

Response will contain the first _n_ number of purchases.

[source,json]
----
{
  "purchases": [
    ....
  ],
  "firstPurchaseHash": "14233908814696HbDrnUNRji5iniGikNLiQ",
  "lastPurchaseHash": "1423390928355zj9yI1wyTvqP46AG8NEaYg",
  "linkUrls": [
        "<https://purchase.izettle.com/purchases/v2?limit=50&descending=true&lastPurchaseHash=1423390928355zj9yI1wyTvqP46AG8NEaYg>; rel=\"next\""
  ]
}
----

To retrieve the next page, use the value of `linkUrls` in the response.

`GET https://purchase.izettle.com/purchases/v2?limit=50&descending=true&lastPurchaseHash=1423390928355zj9yI1wyTvqP46AG8NEaYg`


Response will contain the next _n_ number of purchases.

[source,json]
----
{
  "purchases": [
    ....
  ],
  "firstPurchaseHash": "1423390928355zj9yI1wyTvqP46AG8NEaYg",
  "lastPurchaseHash": "1426265546490RPXdoMmDEeSg5Gw_2s_ZrQ",
  "linkUrls": [
        "<https://purchase.izettle.com/purchases/v2?limit=50&descending=true&lastPurchaseHash=1426265546490RPXdoMmDEeSg5Gw_2s_ZrQ; rel=\"next\""
  ]
}
----

Continue this process by using the `linkUrls` in the previous response as a request parameter in the following request until you receive an empty result.

If you want to be able to load new purchases later on, then store the last used `linkUrls` and use that to continue retrieving new purchases at a later time.
--

* Fetching purchases with partial refund.
+
--
_Request:_

`GET /purchases/v2?&descending=true`

_Response:_

`Status: 200 OK`

[source,json]
----
{
  "purchases": [
    {
      "purchaseUUID": "DpNWkI7EEeaR8yfR3nmUIA",
      "amount": 17000,
      "country": "SE",
      "currency": "SEK",
      "timestamp": "2016-10-10T08:32:23.487+0000",
      "gpsCoordinates": {
        "longitude": 18.06672200650736,
        "latitude": 59.3343190127951,
        "accuracyMeters": 65
      },
      "purchaseNumber": 9,
      "userDisplayName": "Ford Prefect",
      "userId": 1713921,
      "organizationId": 14184411,
      "products": [
        {
          "quantity": "1",
          "unitPrice": 7500,
          "rowTaxableAmount": 7500,
          "name": "Vetelevain",
          "variantName": "Vetelevain",
          "autoGenerated": false,
          "type": "CUSTOM_AMOUNT",
          "id": "Vetelevain_7500",
          "libraryProduct": false
        },
        {
          "quantity": "1",
          "unitPrice": 6000,
          "name": "Källarfranska",
          "variantName": "Källarfranska",
          "autoGenerated": false,
          "type": "CUSTOM_AMOUNT",
          "id": "Källarfranska_6000",
          "libraryProduct": false
        },
        {
          "quantity": "1",
          "unitPrice": 3500,
          "rowTaxableAmount": 3500,
          "name": "Baguette",
          "variantName": "Baguette",
          "autoGenerated": false,
          "type": "CUSTOM_AMOUNT",
          "id": "Baguette_3500",
          "libraryProduct": false
        }
      ],
      "payments": [
       {
         "uuid": "ce90dc90-dcaa-11e6-87a4-0cd119752226",
         "amount": 17000,
         "type": "IZETTLE_CASH",
         "attributes": {
           "handedAmount": 17000
         }
       }
      ],
      "refundedByPurchaseUUIDs": [
        "HKXEKo7EEeaq_0GG8pcFtg"
      ],
      "receiptCopyAllowed": true,
      "published": true,
      "purchaseUUID1": "0e935690-8ec4-11e6-91f3-27d1de799420",
      "refundedByPurchaseUUIDs1": [
        "1ca5c42a-8ec4-11e6-aaff-4186f29705b6"
      ],
      "groupedVatAmounts": {},
      "refund": false,
      "refunded": true
    },
    {
      "purchaseUUID": "HKXEKo7EEeaq_0GG8pcFtg",
      "amount": -3500,
      "country": "SE",
      "currency": "SEK",
      "timestamp": "2016-10-10T08:32:42.675+0000",
      "gpsCoordinates": {
        "longitude": 18.06689298534442,
        "latitude": 59.33430848180441,
        "accuracyMeters": 65
      },
      "purchaseNumber": 10,
      "userDisplayName": "Ford Prefect",
      "userId": 1713921,
      "organizationId": 14184411,
      "products": [
        {
          "quantity": "-1",
          "unitPrice": 3500,
          "rowTaxableAmount": -3500,
          "name": "Baguette",
          "variantName": "Baguette",
          "autoGenerated": false,
          "type": "CUSTOM_AMOUNT",
          "id": "Baguette_3500",
          "libraryProduct": false
        }
      ],
      "payments": [
        {
           "uuid": "1ca7c4f0-8ec4-11e6-93fb-440a20c6bcbf",
           "amount": -3500,
           "type": "IZETTLE_CASH",
           "attributes": {
             "handedAmount": -3500
           }
        }
      ],
      "refundsPurchaseUUID": "DpNWkI7EEeaR8yfR3nmUIA",
      "receiptCopyAllowed": true,
      "published": true,
      "purchaseUUID1": "1ca5c42a-8ec4-11e6-aaff-4186f29705b6",
      "refundsPurchaseUUID1": "0e935690-8ec4-11e6-91f3-27d1de799420",
      "groupedVatAmounts": {},
      "refund": true,
      "refunded": false
    }
  ],
  "firstPurchaseHash": "14297979780492DpNWkI7EEeaR8yfR3nmUIA",
  "lastPurchaseHash": "1476088362675HKXEKo7EEeaq_0GG8pcFtg",
  "linkUrls": [
        "<https://purchase.izettle.com/purchases/v2?limit=10&descending=true&lastPurchaseHash=1476088362675HKXEKo7EEeaq_0GG8pcFtg>; rel=\"next\""
  ]
}
----
--

* Purchases with discounts returned.
+
--

_Request:_

`GET /purchases/v2?&descending=true`

_Response:_

`Status: 200 OK`

[source,json]
----
{
  "purchases": [
    {
      "purchaseUUID": "biqV4OiTEea6-larSAFA7w",
      "amount": 10000,
      "vatAmount": 1331,
      "country": "SE",
      "currency": "SEK",
      "timestamp": "2017-02-01T15:31:00.648+0000",
      "purchaseNumber": 1507,
      "userDisplayName": "Ford Prefect",
      ...
      "products": [
        {
          "quantity": "2",
          "productUuid": "39cde734-e893-11e6-b8f1-2d3db21fba6a",
          "variantUuid": "302b4d5c-e893-11e6-b8f1-2d3db21fba6a",
          "type": "PRODUCT",
          "id" : "0",
          "vatPercentage": 25,
          "unitPrice": 2000,
          "rowTaxableAmount": 2240,
          "name": "Foo",
          "variantName": "",
          "discount": {
            "quantity": 1,
            "amount": 500
          },
          "discountValue": 500,
          "autoGenerated": false,
          "libraryProduct": true
        },
        {
          "quantity": "10",
          "productUuid": "4385c5ee-e893-11e6-b8f1-2d3db21fba6a",
          "variantUuid": "3bdf6232-e893-11e6-b8f1-2d3db21fba6a",
          "type": "PRODUCT",
          "id" : "1",
          "vatPercentage": 12,
          "unitPrice": 1000,
          "rowTaxableAmount": 6429,
          "name": "Bar",
          "variantName": "",
          "discount": {
            "quantity": 1,
            "percentage": 10
          },
          "discountValue": 1000,
          "autoGenerated": false,
          "libraryProduct": true
        }
      ],
      "discounts": [
        {
          "name": "20% off",
          "percentage": 20,
          "quantity": 1
        }
      ],
      "payments": [
        ...
      ],
      ...
      "purchaseUUID1": "6e2a95e0-e893-11e6-bafa-56ab480140ef",
      "groupedVatAmounts": {
        "12.0": 7200,
        "25.0": 2800
      },
      ...
    }
  ],
  "firstPurchaseHash": "1485857753809PaSsMOeeEeawkeLVV_68nw",
  "lastPurchaseHash": "1485858080407AOjsYOefEeax5pDdmnaGXw",
  "linkUrls": [
        "<https://purchase.izettle.com/purchases/v2?limit=10&descending=true&lastPurchaseHash=1485858080407AOjsYOefEeax5pDdmnaGXw>; rel=\"next\""
  ]
}
----
--

'''

====

==== Fetch purchase details

`GET /purchase/v2/{purchaseUuid}`

[%collapsible]
====
Returns a purchase with given UUID.

*Parameters*
[options="header"]
[cols="15%,10%,10%,10%,55%"]
|===
|Name|Type|In|Required/Optional|Description
|purchaseUuid|string|path|required|Unique id of the purchase as UUID within iZettle system.
|===

*Responses*

`Status: 200 OK` - Succesful, response json is returned. +
`Status: 404 Not found` - Purchase with given uuid not found.

*Examples*

* Fetching a specific purchase.
+
--
_Request:_

`GET /purchase/v2/589c2de6-3ee4-11eb-9e70-a2ac075b17fd`

_Response:_

`Status: 200 OK`

[source,json]
----
{
  "source": "POS",
  "purchaseUUID": "WJwt5j7kEeuecKKsB1sX_Q",
  "purchaseUUID1": "589c2de6-3ee4-11eb-9e70-a2ac075b17fd",
  "amount": 70000,
  "vatAmount": 14000,
  "taxAmount": 14000,
  "country": "SE",
  "currency": "SEK",
  "timestamp": "2020-12-15T14:46:43.592+0000",
  "gpsCoordinates": {
    "longitude": 19.80452501310729,
    "latitude": 66.609375,
    "accuracyMeters": 165
  },
  "purchaseNumber": 1366,
  "globalPurchaseNumber": 1366,
  "userDisplayName": "Sara Johansson",
  "userId": 11111,
  "organizationId": 11111,
  "products": [
    {
      "quantity": "1",
      "productUuid": "2f2a8d60-9c76-11e5-8a3b-82916dc77adc",
      "variantUuid": "234ee5f0-b188-11e5-aa17-721c907d3875",
      "vatPercentage": 25,
      "unitPrice": 70000,
      "rowTaxableAmount": 56000,
      "name": "Haircut",
      "variantName": "1 hour",
      "fromLocationUuid": "4c03eec0-183c-11e7-a3f8-037fdcd360ec",
      "toLocationUuid": "4c03eec0-183c-11e7-a15a-cda93ab15db3",
      "autoGenerated": false,
      "id": "0",
      "type": "PRODUCT",
      "libraryProduct": true
    }
  ],
  "discounts": [],
  "payments": [
    {
      "uuid": "592b82f2-3ee4-11eb-9f71-a3ad065a16fc",
      "amount": 70000,
      "type": "SWISH",
      "attributes": {}
    }
  ],
  "receiptCopyAllowed": true,
  "references": {
    "checkoutUUID": "589c2de6-3ee4-11eb-9f71-a3ad065a16fc"
  },
  "taxationMode": "INCLUSIVE",
  "taxationType": "VAT",
  "created": "2020-12-15T14:46:43.592+0000",
  "refunded": false,
  "taxValues": [
    {
      "label": null,
      "taxValue": 25,
      "taxAmount": 14000,
      "totalAmount": 70000
    }
  ],
  "groupedVatAmounts": {
    "25.0": 70000
  },
  "refund": false
}
----
--

'''
====

==== Response Model

Purchase represents a receipt, it's immutable and contains information about items that were purchased, one or several payments received, discounts applied etc.
Refunds are represented by the same model but with negative amounts and refund related flags/fields. +
*Note*: More attributes can potentially be added, please make sure your integration is build in a tolerant way.

*Attributes*
[options="header"]
[cols="15%,10%,75%"]
|===

|Name|Type|Description

|source|string a|Source of purchase, value can be one of the following

* "POS" - purchase made with iZettle GO app
* "WEB_SHOP" - purchase made online
|purchaseUUID|string|Unique id of a purchase within iZettle system.
|purchaseUUID1|string|Unique id of a purchase within iZettle system as UUID version 1.
|timestamp|string|Created timestamp according to the https://en.wikipedia.org/wiki/ISO_8601[ISO 8601] format, e.g. "2019-12-03T17:05:06.123+0000".
|purchaseNumber|integer|Incremental receipt number.
|globalPurchaseNumber|integer|Incremental receipt number, only different from `purchaseNumber` if several cash registers are used by the merchant.
|amount|integer|Gross amount (inc VAT) in minor currency units e.g  €9.95 EUR, amount will be 995. Is negative in case of refund.
|vatAmount|integer|VAT amount for the whole purchase in minor currency units e.g €5 EUR, amount will be 500.
|country|string|Two-letter country code for country the merchant operates in.
|currency|string|Currency code https://en.wikipedia.org/wiki/ISO_4217[ISO 4217]. Examples "SEK", "GBP", "EUR".
|products|array|Describes items that were sold. See section "Products" for more information.
|payments|array|Payments that were processed/received. See section "Payments" for more information.
|discounts|object a|Discounts applied on the whole purchase.
Example:
[source,json]
----
"discounts": [
        {
            "name": "4 for £12",
            "amount": 200,
            "quantity": 1
        }
    ]
or
"discounts": [
        {
            "name": "Staff",
            "percentage": 50,
            "quantity": 1
        }
    ]


----
`name` attribute is optional, not always present.
For more information see section "Discounts".
|serviceCharge|object a|Service charge added to a purchase e.g. delivery charge. +
Example:
[source,json]
----
 "serviceCharge": {
    "amount": 499,
    "title": "Standard Shipping",
    "vatPercentage": 16.0,
    "quantity": "1"
  }
----

|created|string|Created timestamp according to the https://en.wikipedia.org/wiki/ISO_8601[ISO 8601] format e.g. "2019-12-03T17:05:06.123+0000".
|refund|boolean|Indicates if given purchase is a refund.
|refunded|boolean|Indicates if given purchase has been refunded.
|refundsPurchaseUUID|string|Unique id of the purchase that was refunded as string.
|refundsPurchaseUUID1|string|Unique id of the purchase that was refunded as UUID version 1.
|groupedVatAmounts|object a|Contains VAT amounts grouped by percentage. +
Example:
[source, json]
----
"groupedVatAmounts": {
    "25.0": 70000,
    "12.0": 5000
  }
----
|userDisplayName|string|Name of the user that took the payment.
|gpsCoordinates|object a|Contains GPS coordinates of the location where purchase was made. +
Example:
[source,json]
----
"gpsCoordinates": {
    "longitude": 19.80452501310729,
    "latitude": 66.609375,
    "accuracyMeters": 165
  }
----
|userId|integer|Unique id for user within iZettle system.
|cashRegister|object a|Cash register reference. Cash register is a service provided by iZettle and used by merchant in order to comply with requirements coming from the tax authority(only available in Sweden, Norway, Germany and France). +
For now no public API is available for cash register.

Example:
[source,json]
----
"cashRegister": {
    "displayName": "Kassa 2",
    "uuid": "YdVwSn4i111DZepjFuVBw"
}
----
|organizationId|integer|Unique id for organization within iZettle system.
|receiptCopyAllowed|boolean|Indicates if receipt copy is allowed to be printed.
|===

*Products*

A purchase has one or more item rows represented in `products` array.

._Product attributes_
[options="header"]
[cols="10%,10%,80%"]
|===
|Name|Type |Description

|quantity|string|Quantity of items. Can be a whole number or a decimal number, and negative in case of refund.
|type|string a|Describes the kind of item that was purchased. +
Enumeration values:

* "PRODUCT" - Indicates that the item sold was predefined in product library.
* "CUSTOM_AMOUNT" - Indicates that the item sold was a custom amount entered in the app at the time of purchase.
* "GIFTCARD" - Indicates that the item sold was a gift card.

In parallel to the `type` attribute there is an optional `details` attribute that may contain information related to the specific type, for example item lines of type `GIFTCARD` will have a `giftcardUuid` attribute pointing out what gift card that was sold/returned as part of purchases.

|productUuid|string|Unique id of product in product library as UUID.
|name|string|Name of the product sold.
|variantUuid|string|Unique id of variant in product library as UUID.
|variantName|string|Name of variant.
|vatPercentage|number|VAT percentage of the item.
|rowTaxableAmount|integer|Amount on which VAT is chargeable in minor currency units e.g. £12.5 GBP will be 1250.
|unitPrice|integer|Unit price of the item in minor currency units e.g. €10 EUR will be 1000.
|unitName|string|Name of unit e.g. "kg", "hour".
|comment|string|Comment for the item row.
|libraryProduct|boolean|Indicates if product registered in merchant's product library.
|sku|string|SKU of product in inventory.
|barcode|string|Barcode of the product in inventory.
|fromLocationUuid|string|Supplier location id as UUID (inventory).
|toLocationUuid|string|Store location id as UUID (inventory).
|===

'''

*Payments*

A purchase has one or more payments present in `payments` array e.g. purchase can be partially paid in cash and the rest with credit card.
There are several types of payments supported, each of them is described in table "Payment types".

*Note:* Since the product offerings at iZettle change, more payment types could be added.
For forward compatibility it is important that API consumers are implemented in a tolerant way so receiving payments of types that are not yet defined doesn't break integration.


._Payment attributes_
[options="header"]
[cols="10%,10%,80%"]
|===
|Name|Type |Description

|uuid|string|Unique id of the payment in UUID format. Can be linked to
|amount|integer|Amount in minor currency units e.g. £30.50 GBP, amount will be 3050.
|type|string|Payment type used when making a purchase.
|gratuityAmount|integer|Corresponds to the tipping amount in the purchase. This
feature is not available in all supported by iZettle countries. When the `gratuityAmount` is set, the
payment amount will include the gratuity amount.
|attributes|object|Additional information about the payment. Different attributes are included depending on payment type.
|===

._Payment types_
[options="header"]
[cols="30%,70%"]
|===
|Payment type |Description

|IZETTLE_CARD a|Payment taken with iZettle card reader. +

Example:
[source,json]
----
{
  "uuid": "165b88a0-07a3-11e6-9dae-43c30f1bff5b",
  "amount": 2000,
  "gratuityAmount": 0,
  "type": "IZETTLE_CARD",
  "attributes": {
    "cardHolderVerificationMethod": "None",
    "maskedPan": "535583******0000",
    "cardPaymentEntryMode": "CONTACTLESS_EMV",
    "referenceNumber": "B6MFKZTMKP",
    "authorizationCode": "429579",
    "cardType": "MASTERCARD",
    "terminalVerificationResults": "0000008001",
    "applicationIdentifier": "A0000000041010",
    "applicationName": "Debit MasterCard"
  }
}
----
|IZETTLE_CARD_ONLINE a|Payment taken with iZettle online e.g. with payment link.

Example:
[source,json]
----
{
  "uuid": "3d38a2b4-3a02-11eb-bdbf-9f47e7b17f57",
  "amount": 18145,
  "type": "IZETTLE_CARD_ONLINE",
  "attributes": {
    "cardType": "MASTERCARD",
    "maskedPan": "517036******000",
    "cardPaymentEntryMode": "ECOMMERCE",
    "referenceNumber": "PKDBOSWWWW",
    "paymentlinkOrderUuid": "bb6d3b38-3a01-11eb-970c-e3b88c945415"
  }
}
----
|IZETTLE_CASH a|Cash payment registered with iZettle. +

Example:
[source,json]
----
{
  "uuid": "ec138d2e-8e29-41c0-a4c4-17b2b4ab7f8b",
  "amount": 2000,
  "type": "IZETTLE_CASH",
  "attributes": {
    "changeAmount": 3000,
    "handedAmount": 5000
  }
}
----
|IZETTLE_INVOICE a|iZettle invoice is issued for a purchase with this payment type.

Example:
[source,json]
----
{
  "amount": 92250,
  "attributes": {
    "orderUUID": "52201c9a-1234-11eb-9909-5960351f9426",
    "invoiceNr": "iz18",
    "dueDate": "2020-10-29"
  },
  "type": "IZETTLE_INVOICE",
  "uuid": "52372638-1223-11eb-85a4-e6977798fc1e"
}
----
|SWISH|Alternative payment method available in Sweden, has no additional attributes.
|VIPPS|Alternative payment method  available in Norway, has no additional attributes.
|MOBILE_PAY|Alternative payment method available in Denmark, has no additional attributes.
|PAYPAL a| Payment made with PayPal wallet, available in France and Germany.

Example:
[source,json]
----
{
  "uuid": "74d528f1-1bd1-11ed-afd0-27740sse6511",
  "amount": 1200,
  "type": "PAYPAL",
  "attributes": {
    "paypalId": "5TW66818TP9560FFF"
  }
}
----
|STORE_CREDIT|Store credit is usually a document offered by a store to a customer who returns an item not eligible for a refund or when a customer doesn't want to get chargeback on credit card that was used. It can be used to buy other goods at the same store.
|GIFTCARD|Payment made with a gift card(certificate/voucher) issued by the merchant.
|KLARNA a|Alternative payment method available in Sweden, Denmark, Finland and Germany.

Example:
[source,json]
----
{
      "uuid": "fab90e28-c666-4f60-a96b-1515deb88300",
      "receiverOrganization": "1b94d860-6e87-11e8-8345-37e231be703d",
      "amount": 180319,
      "type": "KLARNA",
      "currency": "SEK",
      "country": "SE",
      "referenceNumber": "6B2MFVVDXXX",
      "references": {
        "checkoutUUID": "3431ad48-3ba4-11eb-bc4c-f3c0af76e000"
      },
      "commission": {
        "totalAmount": 5621,
        "vatAmount": 0,
        "vatRate": 17.0,
        "modelId": "4656dbf8-5161-11e9-b86f-74970dafc264",
        "model": {
          "fixed": 590,
          "percentage": 2.79
        }
      },
      "createdAt": "2020-12-11T11:32:14.000+0000",
      "details": {
        "klarnaOrderId": "f7abd5be-04bd-1565-b557-df865f5ba7a0",
        "klarnaProduct": "PAY_LATER",
        "klarnaReference": "029TN5TTT",
        "acquiringChannel": "IN_STORE"
      },
      "attributes": {}
    }
----
|===

'''

*Discounts*

Discounts can exist both on a specific row of items(products), as well as on the entire purchase.
Discount on a row of items is applied on the whole amount of the row, can be set either as a percentage or as a fixed amount.

Items row discounts will be applied first, followed by the discount on the sum of the already discounted row prices.

*VAT calculation on purchase with discounts*

Since each row of items can have a separate VAT percentage the discount
for the whole purchase is evenly distributed over all purchased items.
VAT is calculated after all the discounts are deducted.

If the purchase discount is a fixed amount then that amount  will be deducted from each row according the price of each row in relation to the total purchase price.

*Examples*

If the purchase discount is 20%, then the price of each row of item will be deducted with 20% before calculating the VAT for each row.

If a purchase has a total price of 100 and contains two rows with the first row priced at 40 and the second at 60, then 40% of the fixed purchase discount will be deducted from the first row and 60% from the other row before calculating the VAT.

* Response structure Row discounts are expressed using the following JSON structure in the `products` list, containing either `amount` for fixed discounts or `percentage` for percentage discounts.
The `discountValue` field following the `discount` structure contains the total discount amount for the row:

[source,json]
----
"discount": {
  "name": "10% off",
  "quantity": 1,
  "percentage": 10
},
"discountValue": 1000
----

*Note:* Currently, we only support one discount per row of items, so the `quantity` field will always be set to 1. This could potentially change in the future.

Discounts are represented by using the following JSON structure in the root of the purchase.
They can contain either `amount` or `percentage` value.

[source,json]
----
"discounts": [
{
    "amount": 2000,
    "quantity": 1
}
----

*Note:* Currently, we only support one discount for the whole, so the `discounts` list will only contain one item with `quantity` set to 1. This could potentially change in the future.

See further below for a full response example containing discounts.

*Example*

Let's observe an example purchase, containing both discounts on rows as well as on the purchase itself.

[options="header"]
[cols="3%,20%,20%,20%,27%"]
|===
|Nr|Product|Unit price|Amount|Discount
|1|Foo|20|2|5
|2|Bar|10|10|10%
4+|Purchase discount| 20%
|===

1. To calculate the total discount we start by calculating the discount per row:
+
--
1 st row contains 2 items and a fixed discount amount of 5.

2nd row contains 10 items and a percentage discount of 10%.

*Row discounts* = 5 + 10 x 10 x 0.1 = 15.
--
2. Then we calculate the purchase discount, based on the sum of the previously discounted rows:
+
--
*Sum of discounted rows* = 20 x 2 + 10 x 10 - 15 = 125

*Purchase discount* = 125 x 0.2 = 25

So the total discount on this purchase is 15 + 25 = 40 and the total sum to pay is 140 - 40 = 100.

A discount can never be greater than the actual amount of the row or purchase price.
--

